protontricks dependency removed. Now searches for Proton's wine executable and runs both the installer and BakkesMod through that. Appears to have removed necessity to inject into incompatble version, and the error misleading the user as to a failed injection (fluke?).

diff --git a/BakkesHelper b/BakkesHelper
--- a/BakkesHelper
+++ b/BakkesHelper
@@ -1,5 +1,22 @@
 #!/bin/bash
-function findPrefix(){
+function findWine(){
+	echo Locating Proton wine executable >&2
+	ret="$(cat "$COMPATDIR/config_info" 2>/dev/null | grep -o ".*compatibilitytools.d/[^/]*" | head -1)"
+	if [ -z "$ret" ]; then
+		echo "ERROR: Could not locate Proton wine executable." >&2
+		exit 1
+	fi
+	test -f "$ret/files/bin/wine"
+	if [ "$?" -gt 0 ]; then
+		echo "ERROR: No wine executable found at path specified in $COMPATDIR/config_info" >&2
+		exit 1
+	fi
+	echo "$ret/files/bin/wine"
+}
+
+
+
+function findCompatDir(){
 	echo Locating RocketLeague prefix >&2
 
 
@@ -7,21 +24,23 @@ function findPrefix(){
 	while read -r path; do
 		test -d "$path/steamapps/compatdata/252950/pfx"
 		if [ "$?" -eq 0 ]; then
-			echo "$path/steamapps/compatdata/252950/pfx"
+			echo "$path/steamapps/compatdata/252950"
 			return 0
 		fi
 	done < <(cat ~/".steam/root/steamapps/libraryfolders.vdf" | grep "\"path\"" | grep -oP "[^\s]*$" | sed -s "s/\"//g")
 	echo "No Rocket League installation found." >&2
 	exit 1
 }
+
+
+
 function installBakkes(){
 	# download, unzip latest BakkesMod
 	wget -q --show-progress https://github.com/bakkesmodorg/BakkesModInjectorCpp/releases/latest/download/BakkesModSetup.zip
 	unzip BakkesModSetup.zip
 
 	# launch installer
-	protontricks-launch --appid 252950 BakkesModSetup.exe 2>/dev/null >/dev/null
-
+	WINEPREFIX="$ROCKETDIR" "$ROCKETWINE" "BakkesModSetup.exe"
 
 	# check if installation was successful
 	test -e "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe"
@@ -29,7 +48,7 @@ function installBakkes(){
 		echo "ERROR: BakkesMod not installed for unknown reasons. Maybe user cancelled setup?" >&2
 		return 1
 	else
-		echo "BakkesMod installed successfully."
+		echo "BakkesMod installed successfully." >&2
 
 		# update config file tracking installed version
 		echo "$(git ls-remote --heads https://github.com/bakkesmodorg/BakkesModInjectorCpp | grep refs/heads/master | grep -oP "^[^\s]*")" > ~/.config/bakkes/version
@@ -46,25 +65,36 @@ cd "$(mktemp -d)"
 
 
 # check for dependencies
-which unzip >/dev/null 2>/dev/null || { echo "ERROR: Install unzip from your package manager to continue" 1>&2; exit 1; }
-which git >/dev/null 2>/dev/null || { echo "ERROR: Install git from your package manager to continue" 1>&2; exit 1; }
-which wget >/dev/null 2>/dev/null || { echo "ERROR: Install wget from your package manager to continue" 1>&2; exit 1; }
+which unzip >/dev/null 2>/dev/null || { echo "ERROR: Install unzip from your package manager to continue" >&2; exit 1; }
+which git >/dev/null 2>/dev/null || { echo "ERROR: Install git from your package manager to continue" >&2; exit 1; }
+which wget >/dev/null 2>/dev/null || { echo "ERROR: Install wget from your package manager to continue" >&2; exit 1; }
 
 
 
 # Find Rocket League prefix
-ROCKETDIR="$(findPrefix)"
+COMPATDIR="$(findCompatDir)"
 if [ "$?" -gt 0 ]; then
 	exit 1
 fi
-echo RDIR: $ROCKETDIR
-exit 100
+ROCKETDIR="$COMPATDIR/pfx"
+echo CDIR: $COMPATDIR >&2
+echo RDIR: $ROCKETDIR >&2
+
+
+
+# Find Proton wine executable
+ROCKETWINE="$(findWine)"
+if [ "$?" -gt 0 ]; then
+	exit 1
+fi
+echo RWINE: $ROCKETWINE >&2
+
 
 
 # Check if BakkesMod is installed and if version matches latest release
 test -e "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe"
 if [ "$?" -gt 0 ]; then
-	echo BakkesMod not installed, installing now...
+	echo "BakkesMod not installed, installing now..." >&2
 	installBakkes
 	if [ "$?" -gt 0 ]; then
 		echo Exiting.
@@ -73,22 +103,22 @@ if [ "$?" -gt 0 ]; then
 		echo Success.
 	fi
 else
-	echo Found BakkesMod installation, checking version.
+	echo "Found BakkesMod installation, checking version." >&2
 	BAKKESCURR="$(cat ~/".config/bakkes/version")"
 	BAKKESVER="$(git ls-remote --heads https://github.com/bakkesmodorg/BakkesModInjectorCpp | grep refs/heads/master | grep -oP "^[^\s]*")"
-	echo Remote BakkesMod version: $BAKKESVER
-	echo Current BakkesMod version: $BAKKESCURR
+	echo "Remote BakkesMod version: $BAKKESVER" >&2
+	echo "Current BakkesMod version: $BAKKESCURR" >&2
 	if [ "$BAKKESCURR" != "$BAKKESVER" ]; then
-		echo "BakkesMod Version mismatch, reinstalling."
+		echo "BakkesMod Version mismatch, reinstalling." >&2
 		installBakkes
 		if [ "$?" -gt 0 ]; then
-			echo Exiting.
+			echo "Exiting." >&2
 			exit 1
 		else
-			echo Success.
+			echo "Installed BakkesMod." >&2
 		fi
 	else
-		echo "BakkesMod up to date."
+		echo "BakkesMod up to date." >&2
 	fi
 fi
 
@@ -97,14 +127,14 @@ cd "$(mktemp -d)"
 cat > runner.sh << EOF
 #!/bin/bash
 while [ -z "\$(ps -e | grep RocketLeague)" ]; do
-		echo Waiting for user to start RocketLeague	
+		echo Waiting for user to start RocketLeague >&2
 		sleep 2
 done
-echo RocketLeague launched
+echo RocketLeague launched >&2
 sleep 20
-protontricks-launch --appid 252950 "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe" 2>/dev/null >/dev/null &
+WINEPREFIX="$ROCKETDIR" "$ROCKETWINE" "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe" &
 while [ ! -z "\$(ps -e | grep RocketLeague)" ]; do
-	echo RocketLeague still running.
+	echo RocketLeague still running. >&2
 	sleep 10
 done
 pkill -e BakkesMod
