Fixed bug where Steam's LD_PRELOAD would prevent git from using system's libcurl, making it impossible to get the remote BakkesMod version

diff --git a/BakkesHelper b/BakkesHelper
--- a/BakkesHelper
+++ b/BakkesHelper
@@ -1,16 +1,16 @@
 #!/bin/bash
 function findWine(){
-	echo Locating Proton wine executable >&2
+	echo "BakkesHelper: Locating Proton wine executable" >&2
 	ret="$(cat "$COMPATDIR/config_info" 2>/dev/null | head -2 | tail -1 | sed -s "s@/share/fonts/@@")"
-	echo ret: $ret >&2
+	echo BakkesHelper: ret: $ret >&2
 	#ret="$(cat "$COMPATDIR/config_info" 2>/dev/null | head -2 | tail -1 | grep -o ".*compatibilitytools.d/[^/]*" | head -1)"
 	if [ -z "$ret" ]; then
-		echo "ERROR: Could not locate Proton wine executable." >&2
+		echo "BakkesHelper: ERROR: Could not locate Proton wine executable." >&2
 		exit 1
 	fi
 	test -f "$ret/bin/wine"
 	if [ "$?" -gt 0 ]; then
-		echo "ERROR: No wine executable found at path specified in $COMPATDIR/config_info" >&2
+		echo "BakkesHelper: ERROR: No wine executable found at path specified in $COMPATDIR/config_info" >&2
 		exit 1
 	fi
 	echo "$ret/bin/wine"
@@ -19,7 +19,7 @@ function findWine(){
 
 
 function findCompatDir(){
-	echo Locating RocketLeague prefix >&2
+	echo "BakkesHelper: Locating RocketLeague prefix" >&2
 
 
 	# check all steam library directories mentioned in libraryfolders.vdf for Rocket League prefix, return the first instance found or error out
@@ -30,7 +30,7 @@ function findCompatDir(){
 			return 0
 		fi
 	done < <(cat ~/".steam/root/steamapps/libraryfolders.vdf" | grep "\"path\"" | grep -oP "[^\s]*$" | sed -s "s/\"//g")
-	echo "No Rocket League installation found." >&2
+	echo "BakkesHelper: No Rocket League installation found." >&2
 	exit 1
 }
 
@@ -47,13 +47,14 @@ function installBakkes(){
 	# check if installation was successful
 	test -e "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe"
 	if [ "$?" -gt 0 ]; then
-		echo "ERROR: BakkesMod not installed for unknown reasons. Maybe user cancelled setup?" >&2
+		echo "BakkesHelper: ERROR: BakkesMod not installed for unknown reasons. Maybe user cancelled setup?" >&2
 		return 1
 	else
-		echo "BakkesMod installed successfully." >&2
+		echo "BakkesHelper: BakkesMod installed successfully." >&2
 
 		# update config file tracking installed version
-		echo "$(git ls-remote --heads https://github.com/bakkesmodorg/BakkesModInjectorCpp | grep refs/heads/master | grep -oP "^[^\s]*")" > ~/.config/bakkes/version
+		echo "$BAKKESVER" > ~/".config/bakkes/version"
+		echo "BakkesHelper: Config updated to reflect current version: $BAKKESVER" >&2
 		return 0
 	fi
 }
@@ -67,9 +68,9 @@ cd "$(mktemp -d)"
 
 
 # check for dependencies
-which unzip >/dev/null 2>/dev/null || { echo "ERROR: Install unzip from your package manager to continue" >&2; exit 1; }
-which git >/dev/null 2>/dev/null || { echo "ERROR: Install git from your package manager to continue" >&2; exit 1; }
-which wget >/dev/null 2>/dev/null || { echo "ERROR: Install wget from your package manager to continue" >&2; exit 1; }
+which unzip >/dev/null 2>/dev/null || { echo "BakkesHelper: ERROR: Install unzip from your package manager to continue" >&2; exit 1; }
+which git >/dev/null 2>/dev/null || { echo "BakkesHelper: ERROR: Install git from your package manager to continue" >&2; exit 1; }
+which wget >/dev/null 2>/dev/null || { echo "BakkesHelper: ERROR: Install wget from your package manager to continue" >&2; exit 1; }
 
 
 
@@ -79,8 +80,8 @@ if [ "$?" -gt 0 ]; then
 	exit 1
 fi
 ROCKETDIR="$COMPATDIR/pfx"
-echo CDIR: $COMPATDIR >&2
-echo RDIR: $ROCKETDIR >&2
+echo "BakkesHelper: CDIR: $COMPATDIR" >&2
+echo "BakkesHelper: RDIR: $ROCKETDIR" >&2
 
 
 
@@ -89,13 +90,28 @@ ROCKETWINE="$(findWine)"
 if [ "$?" -gt 0 ]; then
 	exit 1
 fi
-echo RWINE: $ROCKETWINE >&2
+echo "BakkesHelper: RWINE: $ROCKETWINE" >&2
 
 
 # Check if BakkesMod is installed and if version matches latest release
+BAKKESCURR="$(cat ~/".config/bakkes/version")"
+BAKKESVER="$(LD_PRELOAD="" LD_LIBRARY_PATH="" git ls-remote --heads "https://github.com/bakkesmodorg/BakkesModInjectorCpp" | grep "refs/heads/master" | grep -oP "^[^\s]*")"
+attempts=5
+while [ -z "$BAKKESVER" ]; do
+	echo "BakkesHelper: ERROR: Could not get remote BakkesMod version from official repo (no internet connection?), retrying..." >&2
+	sleep 5
+	if [ "$attempts" -gt 0 ]; then
+		attempts="$(($attempts-1))"
+	else
+		
+		echo "BakkesHelper: ERROR: Could not get remote BakkesMod version from official repo (no internet connection?), giving up." >&2
+		exit 1
+	fi
+	BAKKESVER="$(LD_PRELOAD="" LD_LIBRARY_PATH="" git ls-remote --heads "https://github.com/bakkesmodorg/BakkesModInjectorCpp" | grep "refs/heads/master" | grep -oP "^[^\s]*")"
+done
 test -e "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe"
 if [ "$?" -gt 0 ]; then
-	echo "BakkesMod not installed, installing now..." >&2
+	echo "BakkesHelper: BakkesMod not installed, installing now..." >&2
 	installBakkes
 	if [ "$?" -gt 0 ]; then
 		echo Exiting.
@@ -104,22 +120,20 @@ if [ "$?" -gt 0 ]; then
 		echo Success.
 	fi
 else
-	echo "Found BakkesMod installation, checking version." >&2
-	BAKKESCURR="$(cat ~/".config/bakkes/version")"
-	BAKKESVER="$(git ls-remote --heads https://github.com/bakkesmodorg/BakkesModInjectorCpp | grep refs/heads/master | grep -oP "^[^\s]*")"
-	echo "Remote BakkesMod version: $BAKKESVER" >&2
-	echo "Current BakkesMod version: $BAKKESCURR" >&2
+	echo "BakkesHelper: Found BakkesMod installation, checking version." >&2
+	echo "BakkesHelper: Remote BakkesMod version: $BAKKESVER" >&2
+	echo "BakkesHelper: Current BakkesMod version: $BAKKESCURR" >&2
 	if [ "$BAKKESCURR" != "$BAKKESVER" ]; then
-		echo "BakkesMod Version mismatch, reinstalling." >&2
+		echo "BakkesHelper: BakkesMod Version mismatch, reinstalling." >&2
 		installBakkes
 		if [ "$?" -gt 0 ]; then
-			echo "Exiting." >&2
+			echo "BakkesHelper: Exiting." >&2
 			exit 1
 		else
-			echo "Installed BakkesMod." >&2
+			echo "BakkesHelper: Installed BakkesMod." >&2
 		fi
 	else
-		echo "BakkesMod up to date." >&2
+		echo "BakkesHelper: BakkesMod up to date." >&2
 	fi
 fi
 
@@ -128,16 +142,17 @@ cd "$(mktemp -d)"
 cat > runner.sh << EOF
 #!/bin/bash
 while [ -z "\$(ps -e | grep RocketLeague)" ]; do
-		echo Waiting for user to start RocketLeague >&2
+		echo "BakkesHelper: Waiting for user to start RocketLeague" >&2
 		sleep 2
 done
-echo RocketLeague launched >&2
+echo "BakkesHelper: RocketLeague launched" >&2
 sleep 20
 WINEPREFIX="$ROCKETDIR" "$ROCKETWINE" "$ROCKETDIR/drive_c/Program Files/BakkesMod/BakkesMod.exe" &
 while [ ! -z "\$(ps -e | grep RocketLeague)" ]; do
-	echo RocketLeague still running. >&2
+	echo "BakkesHelper: RocketLeague still running." >&2
 	sleep 10
 done
+echo "BakkesHelper: Rocket League close, shutting down." >&2
 pkill -e BakkesMod
 EOF
 chmod +x runner.sh
